"""Frozen Phase 7 campaign and export contracts."""

from __future__ import annotations

CAMPAIGN_CONTRACT_VERSION = "1"
CAMPAIGN_EXPORT_CONTRACT_VERSION = "1"
CAMPAIGN_MEMBER_RESOLUTION_CONTRACT_VERSION = "1"

CAMPAIGN_STATUS_DRAFT = "DRAFT"
CAMPAIGN_STATUS_FINALIZED = "FINALIZED"
CAMPAIGN_STATUSES = (CAMPAIGN_STATUS_DRAFT, CAMPAIGN_STATUS_FINALIZED)

CAMPAIGN_CHANNEL_EMAIL = "EMAIL"
CAMPAIGN_CHANNEL_DIRECT_MAIL = "DIRECT_MAIL"
CAMPAIGN_CHANNELS = (CAMPAIGN_CHANNEL_EMAIL, CAMPAIGN_CHANNEL_DIRECT_MAIL)

EXPORT_PROFILE_EMAIL_CONTACT_V1 = "EMAIL_CONTACT_V1"
EXPORT_PROFILE_DIRECT_MAIL_CONTACT_V1 = "DIRECT_MAIL_CONTACT_V1"

BASE_EXPORT_COLUMNS = (
    "person_id",
    "propensity_score",
    "percentile_bucket",
    "decile",
    "rank_band",
)

EMAIL_EXPORT_COLUMNS = (
    *BASE_EXPORT_COLUMNS,
    "first_name",
    "last_name",
    "email",
)

DIRECT_MAIL_EXPORT_COLUMNS = (
    *BASE_EXPORT_COLUMNS,
    "first_name",
    "last_name",
    "address_line_1",
    "address_line_2",
    "city",
    "state",
    "postal_code",
)

PROHIBITED_EXPORT_FIELDS = (
    "ethnicity",
    "religion",
    "occupation_industry",
    "family_yearly_income",
    "number_of_children_in_family",
    "number_of_adults_in_family",
    "customer_id",
    "phone_number",
)

CHANNEL_EXPORT_PROFILE = {
    CAMPAIGN_CHANNEL_EMAIL: EXPORT_PROFILE_EMAIL_CONTACT_V1,
    CAMPAIGN_CHANNEL_DIRECT_MAIL: EXPORT_PROFILE_DIRECT_MAIL_CONTACT_V1,
}

PROFILE_EXPORT_COLUMNS = {
    EXPORT_PROFILE_EMAIL_CONTACT_V1: EMAIL_EXPORT_COLUMNS,
    EXPORT_PROFILE_DIRECT_MAIL_CONTACT_V1: DIRECT_MAIL_EXPORT_COLUMNS,
}

__all__ = (
    "BASE_EXPORT_COLUMNS",
    "CAMPAIGN_CHANNELS",
    "CAMPAIGN_CHANNEL_DIRECT_MAIL",
    "CAMPAIGN_CHANNEL_EMAIL",
    "CAMPAIGN_CONTRACT_VERSION",
    "CAMPAIGN_EXPORT_CONTRACT_VERSION",
    "CAMPAIGN_MEMBER_RESOLUTION_CONTRACT_VERSION",
    "CAMPAIGN_STATUSES",
    "CAMPAIGN_STATUS_DRAFT",
    "CAMPAIGN_STATUS_FINALIZED",
    "CHANNEL_EXPORT_PROFILE",
    "DIRECT_MAIL_EXPORT_COLUMNS",
    "EMAIL_EXPORT_COLUMNS",
    "EXPORT_PROFILE_DIRECT_MAIL_CONTACT_V1",
    "EXPORT_PROFILE_EMAIL_CONTACT_V1",
    "PROFILE_EXPORT_COLUMNS",
    "PROHIBITED_EXPORT_FIELDS",
)
