"""Frozen Phase 7 campaign and export contracts."""

from __future__ import annotations

from app.services.omnichannel_profile_contracts import (
    BASE_EXPORT_COLUMNS,
    CAMPAIGN_CHANNEL_DIRECT_MAIL,
    CAMPAIGN_CHANNEL_EMAIL,
    COMMON_PROHIBITED_EXPORT_FIELDS,
    EXPORT_PROFILE_DIRECT_MAIL_CONTACT_V1,
    EXPORT_PROFILE_EMAIL_CONTACT_V1,
    OMNICHANNEL_PROFILE_REGISTRY,
)

CAMPAIGN_CONTRACT_VERSION = "1"
CAMPAIGN_EXPORT_CONTRACT_VERSION = "1"
CAMPAIGN_MEMBER_RESOLUTION_CONTRACT_VERSION = "1"

CAMPAIGN_STATUS_DRAFT = "DRAFT"
CAMPAIGN_STATUS_FINALIZED = "FINALIZED"
CAMPAIGN_STATUSES = (CAMPAIGN_STATUS_DRAFT, CAMPAIGN_STATUS_FINALIZED)

# The legacy Campaign workflow remains deliberately limited until the Phase 11
# result export engine is implemented.  The backend-owned omnichannel registry
# is the authority for the expanded profile surface.
CAMPAIGN_CHANNELS = (CAMPAIGN_CHANNEL_EMAIL, CAMPAIGN_CHANNEL_DIRECT_MAIL)

EMAIL_EXPORT_COLUMNS = OMNICHANNEL_PROFILE_REGISTRY[
    EXPORT_PROFILE_EMAIL_CONTACT_V1
].output_columns
DIRECT_MAIL_EXPORT_COLUMNS = OMNICHANNEL_PROFILE_REGISTRY[
    EXPORT_PROFILE_DIRECT_MAIL_CONTACT_V1
].output_columns

# Compatibility name for common prohibitions only.  Contact identifiers such
# as phone/email are governed by each profile's exact allowlist/prohibited set;
# they are intentionally not globally prohibited or globally permitted.
PROHIBITED_EXPORT_FIELDS = COMMON_PROHIBITED_EXPORT_FIELDS
PROFILE_PROHIBITED_FIELDS = {
    name: profile.prohibited_fields
    for name, profile in OMNICHANNEL_PROFILE_REGISTRY.items()
}

CHANNEL_EXPORT_PROFILE = {
    CAMPAIGN_CHANNEL_EMAIL: EXPORT_PROFILE_EMAIL_CONTACT_V1,
    CAMPAIGN_CHANNEL_DIRECT_MAIL: EXPORT_PROFILE_DIRECT_MAIL_CONTACT_V1,
}

PROFILE_EXPORT_COLUMNS = {
    name: profile.output_columns
    for name, profile in OMNICHANNEL_PROFILE_REGISTRY.items()
}

__all__ = (
    "BASE_EXPORT_COLUMNS",
    "CAMPAIGN_CHANNELS",
    "CAMPAIGN_CHANNEL_DIRECT_MAIL",
    "CAMPAIGN_CHANNEL_EMAIL",
    "CAMPAIGN_CONTRACT_VERSION",
    "CAMPAIGN_EXPORT_CONTRACT_VERSION",
    "CAMPAIGN_MEMBER_RESOLUTION_CONTRACT_VERSION",
    "CAMPAIGN_STATUSES",
    "CAMPAIGN_STATUS_DRAFT",
    "CAMPAIGN_STATUS_FINALIZED",
    "CHANNEL_EXPORT_PROFILE",
    "DIRECT_MAIL_EXPORT_COLUMNS",
    "EMAIL_EXPORT_COLUMNS",
    "EXPORT_PROFILE_DIRECT_MAIL_CONTACT_V1",
    "EXPORT_PROFILE_EMAIL_CONTACT_V1",
    "PROFILE_EXPORT_COLUMNS",
    "PROFILE_PROHIBITED_FIELDS",
    "PROHIBITED_EXPORT_FIELDS",
)
